Metrics/LineLength:
  Max: 160
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Include:
    - lib/**
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'fasten.gemspec'
Metrics:
  Exclude:
    - 'lib/fasten/ui/curses.rb'
Naming:
  Exclude:
    - 'lib/fasten/ui/curses.rb'
Style:
  Exclude:
    - 'lib/fasten/ui/curses.rb'
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 15
Metrics/ParameterLists:
  Max: 8
Layout/AlignHash:
  EnforcedHashRocketStyle: table
Style/FormatStringToken:
  Enabled: false
