AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 45
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 14
Metrics/MethodLength:
  Max: 40
Metrics/PerceivedComplexity:
  Max: 14

Style/Documentation:
  Enabled: false
