Metrics/LineLength:
  Max: 160
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Include:
    - lib/**
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Metrics/AbcSize:
  Max: 17
Metrics/MethodLength:
  Max: 15
